#!/bin/sh
# Copyright sociomantic labs GmbH 2017.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
set -xeu

# Test help
beaver docker gen-dockerfile -h | grep 'Usage:'

# Test basic usage
export DIST=
beaver docker gen-dockerfile > Dockerfile
cat Dockerfile
grep -q "FROM.*:$(lsb_release -cs)-v2" Dockerfile # Check for the host's DIST
beaver docker build .
rm Dockerfile
beaver docker run test -f /DOCKER-RUN-CALLED -a -f /BUILD-SCRIPT-CALLED
test "$(beaver docker run lsb_release -cs)" = "$(lsb_release -cs)"

# Test basic usage but with DIST env var
test_basic_dist()
{
    export DIST="$1"
    beaver docker gen-dockerfile > Dockerfile2
    cat Dockerfile2
    grep -q "FROM.*:$DIST-v2" Dockerfile2
    beaver docker build -f Dockerfile2 .
    rm Dockerfile2
    beaver docker run test -f /DOCKER-RUN-CALLED -a -f /BUILD-SCRIPT-CALLED
    test "$(beaver docker run lsb_release -cs)" = "$DIST"
}

test_basic_dist xenial
