# Copyright dunnhumby Germany GmbH 2018.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
#
# This Dockerfile is just for testing
FROM sociomantictsunami/dlang:xenial-v2
RUN touch /BUILT-img2-Dockerfile
COPY img2/build /BUILT-img2-Dockerfile-COPY
RUN /BUILT-img2-Dockerfile-COPY
