#!/bin/sh
# Copyright dunnhumby Germany GmbH 2018.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
set -xeu

test_run()
{
    args=
    if test "${2:-}" = "pass-args"
    then
        args="--docker-img img${1} --docker-context=img${1}"
    fi
    true "--------------------"
    echo "Running test on img${1}..."
    beaver $args docker run test -f /BUILT-img${1}-Dockerfile -a \
            -f /BUILT-img${1}-Dockerfile-COPY -a \
            -f /BUILT-img${1}-build
    beaver $args docker run cat /BUILT-img${1}-Dockerfile-COPY
    cat img${1}/build
    md5real=$(beaver $args docker run cat /BUILT-img${1}-Dockerfile-COPY |
            md5sum)
    test "$md5real" = "$(md5sum < img${1}/build)"
}

# Use xenial
export DIST=xenial

# Build and run first image (with beaver.Dockerfile)
export BEAVER_DOCKER_IMG=img1 BEAVER_DOCKER_CONTEXT=img1
beaver install
cat beaver.Dockerfile.generated
cat img1/beaver.Dockerfile.generated.expected
test "$(md5sum < beaver.Dockerfile.generated)" = \
        "$(md5sum < img1/beaver.Dockerfile.generated.expected)"
rm beaver.Dockerfile.generated
test_run 1

true "======================================================================="
# Build and run second image (with Dockerfile.xenial)
export BEAVER_DOCKER_IMG=img2 BEAVER_DOCKER_CONTEXT=img2
beaver install
test_run 2

true "======================================================================="
# Build and run first first image with dlang install
export BEAVER_DOCKER_IMG=img1 BEAVER_DOCKER_CONTEXT=img1
DMD=dmd1 beaver dlang install
test_run 1

true "======================================================================="
# Build and run second image (with Dockerfile.xenial)
beaver --docker-img img2 --docker-context=img2 install
test_run 2 pass-args

true "======================================================================="
# Build and run first first image with dlang install
DMD=dmd1 beaver --docker-img img1 --docker-context=img1 dlang install
test_run 1 pass-args

true "======================================================================="
# Interleaved runs between both images
BEAVER_DOCKER_IMG=img2 test_run 2
BEAVER_DOCKER_IMG=img2 test_run 2
BEAVER_DOCKER_IMG=img1 test_run 1

echo $BEAVER_DOCKER_IMG $BEAVER_DOCKER_CONTEXT
beaver install # Creates img1 again (no dlang)
BEAVER_DOCKER_IMG=img1 test_run 1
BEAVER_DOCKER_IMG=img2 test_run 2
